import { NextApiRequest, NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.scss";
import cookie from "cookie";
import CreateComponent from "../component/create";


type Props = {
  token: string;
};

const Create: NextPage<Props> = ({ token }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create title</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CreateComponent token={token} />
    </div>
  );
};

export const getServerSideProps = async ({ req }: { req: NextApiRequest }) => {
  const parseCookies = (req: NextApiRequest) => {
    return cookie.parse(req ? req.headers.cookie || "" : "");
  };
  const { token } = parseCookies(req);

  return token
    ? {
        props: {
          token,
        },
      }
    : {
        props: {},
      };
};

export default Create;
