import Head from "next/head";
import styles from "../styles/Home.module.scss";
import cookie from "cookie";
import { NextApiRequest, NextPage } from "next";
import PaginationComponent from "../component/pagination";
import TableSort from "../component/table";

type Props = {
  token: string;
};

const Home: NextPage<Props> = ({ token }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Home title</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TableSort token={token} />
      {/* <Pagination className={styles.pagination} total={10} /> */}
      <PaginationComponent />
    </div>
  );
};

export const getServerSideProps = async ({ req }: { req: NextApiRequest }) => {
  const parseCookies = (req: NextApiRequest) => {
    return cookie.parse(req ? req.headers.cookie || "" : "");
  };
  const { token } = parseCookies(req);

  return token
    ? {
        props: {
          token,
        },
      }
    : {
        props: {},
      };
};

export default Home;
