import Head from "next/head";
import styles from "../styles/Home.module.scss";
import { TableSort } from "../component/table";
import cookie from "cookie";
import { GetServerSideProps, NextApiRequest, NextPage } from "next";
import { Pagination } from "@mantine/core";

type Props = {
  token: string;
};

const Home: NextPage<Props> = ({ token }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Home title</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TableSort token={token} />
      <Pagination className={styles.pagination} total={10} />
    </div>
  );
};

export const getServerSideProps = async ({ req }: { req: NextApiRequest }) => {
  const parseCookies = (req: NextApiRequest) => {
    return cookie.parse(req ? req.headers.cookie || "" : "");
  };
  const { token } = parseCookies(req);

  return token
    ? {
        props: {
          token,
        },
      }
    : {
        props: {},
      };
};

// export const getServerSideProps = async ({ req }) => {
//   const parseCookies = (req) => {
//     return cookie.parse(req ? req.headers.cookie || "" : "");
//   };
//   const { token } = parseCookies(req);

//   return token
//     ? {
//         props: {
//           token,
//         },
//       }
//     : {
//         props: {},
//       };
// };

export default Home;
