import {
  GetServerSideProps,
  GetServerSidePropsContext,
  NextPage,
} from "next";
import cookie from "cookie";
import Head from "next/head";
import styles from "../../styles/Home.module.scss";
import DetailComponent from "../../component/detail";
import { IncomingMessage } from "http";

type Props = {
  token: string;
  id: number;
};

const DetailPage: NextPage<Props> = ({ token, id }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Detail title</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DetailComponent token={token} id={id} />
    </div>
  );
};

type Req = {
  headers: {
    cookie: string;
  };
};

export const getServerSideProps: GetServerSideProps = async (
  context: GetServerSidePropsContext
) => {
  const req : IncomingMessage= context.req;
  const id = context.params && context.params.id;
  const parseCookies = (req: IncomingMessage) => {
    return cookie.parse(req ? req.headers.cookie || "" : "");
  };
  const { token } = parseCookies(req);

  return token
    ? {
        props: {
          token,
          id,
        },
      }
    : {
        props: {
          id,
        },
      };
};

export default DetailPage;
